In [1]:
f = open('day1_input.txt')
lines = f.readlines()
nums = [int(num) for num in lines]
f.close()

# Part 1

This is a "**two-sum**" problem: to find two numbers that sum to 2020, from the input as following:

In [2]:
print(f'There are {len(nums)} numbers in the input, the first 10 numbers are:')
print(nums[0:10])

There are 200 numbers in the input, the first 10 numbers are:
[997, 1582, 1790, 1798, 1094, 1831, 1879, 1730, 1995, 1702]


There are many ways to do it, and one is as following:

In [3]:
for n1 in nums:
    n2 = 2020-n1
    if n2 in nums:
        print(f'{n1} + {n2} = {n1 + n2}')

679 + 1341 = 2020
1341 + 679 = 2020


Looks like there is only one pair of numbers which sum to 2020: 679 and 1341.

For Day 1 part 1, we need to multiply the two:

In [4]:
679*1341

910539

# Part 2

Now it's a "**Three-sum**" problem: to find three numbers that sum to 2020, from the same input. A lazy way is simply to add one more layer to the two-sum solution above, considering the input is not that large (only 200 entries):

In [5]:
for n1 in nums:
    two_sum = 2020-n1
    for n2 in nums:
        n3 = two_sum - n2
        if n3 in nums:
            print(f'{n1} + {n2} + {n3} = {n1+n2+n3}')

912 + 977 + 131 = 2020
912 + 131 + 977 = 2020
977 + 912 + 131 = 2020
977 + 131 + 912 = 2020
131 + 912 + 977 = 2020
131 + 977 + 912 = 2020


Well, looks like there is only one set of numbers will sum to 2020: 131, 912, and 977.

And the product of the three are:

In [6]:
131 * 912 * 977

116724144